### ISSUE TITLE
Performance regression on magit-status

### ISSUE THREAD

**Issue by Niluge-KiWi** [emacsorphanage/magit-svn#1]
On current `next` branch there is a performance regression on `magit-status`: it takes a noticeable time to open the buffer when `magit-svn` is enabled.

I tracked it down to this cleanup commit: magit/magit@b583e43a57dee164fdd53e0772220e32c1b3fab3

The commit message express surprise about a cache on `magit-svn-get-ref-info`, but this cache was justified: git svn commands are slow (~100-200ms).

`elp` benchmarks (with untracked-files section removed to not pollute results).

`elp-results` on `magit` with current code: (after several runs)

```
Function Name                            Call Count  Elapsed Time  Average Time
magit-status                             1           0.76897946    0.76897946
magit-status-internal                    1           0.766762562   0.766762562
magit-mode-init                          1           0.763225231   0.763225231
magit-refresh-buffer                     1           0.759236451   0.759236451
magit-status-refresh-buffer              1           0.759183503   0.759183503
magit-git-lines                          4           0.4915132050  0.1228783012
magit-svn-get-ref                        2           0.355030509   0.1775152545
magit-insert-status-headers              1           0.271441163   0.271441163
magit-insert-svn-remote                  1           0.251769731   0.251769731
magit-insert-svn-unpulled                1           0.180940436   0.180940436
magit-insert-svn-unpushed                1           0.179538607   0.179538607
magit-git-string                         28          0.1706065320  0.0060930904
magit-svn-get-rev                        1           0.134984161   0.134984161
magit-svn-get-url                        1           0.11667238    0.11667238
magit-git-insert                         5           0.070193878   0.0140387756
magit-insert-unstaged-changes            1           0.039062375   0.039062375
magit-rev-parse                          14          0.0249038829  0.0017788487
magit-git-exit-code                      1           0.022514062   0.022514062
magit-insert-staged-changes              1           0.022456032   0.022456032
magit-insert-stashes                     1           0.017045697   0.017045697
magit-git-dir                            9           0.0149849270  0.0016649918
magit-git-wash                           5           0.014471964   0.0028943928
magit-get-tracked-branch                 3           0.013940774   0.0046469246
magit-get                                7           0.011941633   0.0017059475
magit-log-wash-log                       1           0.010634437   0.010634437
...
```

`elp-results` on `magit` with code before regression:

```
Function Name                            Call Count  Elapsed Time  Average Time
magit-status                             1           0.177979385   0.177979385
magit-status-internal                    1           0.175815083   0.175815083
magit-mode-init                          1           0.172362305   0.172362305
magit-refresh-buffer                     1           0.153528527   0.153528527
magit-status-refresh-buffer              1           0.15348111    0.15348111
magit-git-insert                         6           0.0577031540  0.0096171923
magit-git-string                         30          0.0560343130  0.0018678104
magit-insert-stashes                     1           0.03618378    0.03618378
magit-git-wash                           5           0.033645435   0.006729087
magit-log-wash-log                       1           0.030064118   0.030064118
magit-wash-sequence                      1           0.028428347   0.028428347
magit-log-wash-line                      87          0.0282701109  0.0003249438
magit-insert-status-headers              1           0.026541123   0.026541123
magit-insert-unstaged-changes            1           0.026058915   0.026058915
magit-rev-parse                          14          0.023811016   0.0017007868
magit-format-log-margin                  87          0.0234701749  0.0002697721
magit-insert-staged-changes              1           0.022075899   0.022075899
magit-status-mode                        1           0.018823322   0.018823322
magit-get                                10          0.015855973   0.0015855972
magit-git-dir                            9           0.014416526   0.0016018362
magit-get-tracked-branch                 3           0.013425226   0.0044750753
magit-git-exit-code                      1           0.012818424   0.012818424
...
```

The new version seems to call 4 times some git svn commands, and each one takes >100ms.
Old 200ms load time is almost not noticeable, new 700ms load time _is_.

We need this cache, at least until git svn is faster (I will bug report on git for that).

**Comment by Niluge-KiWi** [comment]
@tarsius have you seen this? I don't know it you have notifications for this repo or not, since it's the first issue here.

**Comment by tarsius** [comment]
Yeah.

**Comment by tarsius** [comment]
@Niluge-KiWi sorry for the long delay.

Please test whether #3 fixes the performance issue and has no other problems. Thanks.

**Comment by Niluge-KiWi** [comment]
My scenario:  `magit-status` from the repo directory, with no previous magit-status buffer.

#3 removes one of the two calls to `git svn info`, so we gain ~110ms out of the ~220ms for `magit-svn-get-url` and `magit-svn-get-rev`.

However, there are still two calls to `magit-svn-get-ref` for ~350ms, which were not present at all prior to magit/magit@b583e43 (it seems they were re-computed by magit-svn as git-svn does itself, which is not great, but if it takes a lot less than 350ms, then it's definitely useful).

Even if `magit-svn-get-ref` is also cached, we are still talking about 175ms for it + 110ms for info-cache, so ~300ms whereas the previous implementation (that re-implemented git-svn from perl to lisp) took less than 12ms from my previous elp trace.

I (or someone else) still have to bug report the performance issue to git-svn maintainers though. If they can fix this it would be a lot easier for magit.

**Comment by tarsius** [comment]
> I (or someone else) still have to bug report the performance issue to git-svn maintainers though. If they can fix this it would be a lot easier for magit.

That's always my preferred approach :-)

**Comment by Niluge-KiWi** [comment]
Bug reported on the git ML:
http://thread.gmane.org/gmane.comp.version-control.git/262332
Le 12 janv. 2015 21:20, "Jonas Bernoulli" notifications@github.com a
écrit :

**Comment by Niluge-KiWi** [comment]
@tarsius on the git ML thread I asked if git-svn could have a better porcelain command-line API for easier integration in frontends, like git itself has.
I think it could be useful as we currently do indirect commands to get what we need (I'm thinking about `git svn rebase --dry-run` to get the remote branch ref).

They asked what exact features would be required. Could you weigh in on this on the git ML thread?

**Comment by tarsius** [comment]
I don't think I can contribute much to the discussion. I only ever use `magit-svn` to test some changes, hoping that it is the last time I have to do because someone volunteers to become the new maintainer.

So I don't know what features would make sense beyond what's already provided.
