### ISSUE TITLE
magit + transient changes break magit-svn

### ISSUE THREAD

**Issue by jeffpollock9** [emacsorphanage/magit-svn#10]
as discussed [here on reddit](https://www.reddit.com/r/emacs/comments/aqp6jc/transient_released_magitpopup_successor/egiruhh) there are some problems using magit-svn with the latest magit/transient.

Many thanks for looking at this, @tarsius, but I still cannot get it to work and get this error now after updating:

```
magit-insert-svn-remote: Invalid function: (value (run-hook-with-args-until-success (quote magit-section-set-visibility-hook) section5))
```

Please let me know if there is anything I can do to help.

**Comment by tarsius** [comment]
That's not related but due to https://github.com/magit/magit/pull/3649.

**Comment by jeffpollock9** [comment]
That’s amazing - thank you!
