### ISSUE TITLE
Get reference info for differently named remote

### ISSUE THREAD

**Issue by Kurvivor19** [emacsorphanage/magit-svn#11]
In certain cases there are several differently-named [svn-remote ...] sections in git config, for example when repository layout is not standard. In that case, magit-svn cannot retrieve revision info, because in `magit-svn-get-ref-info` the data retrieval call is made with:

`(magit-get "svn-remote" "svn" "fetch")`

While overall functionality works, it makes it harder to properly see differences in states of local repository and upstream.

Can it be generalized to go over all known svn remotes?

**Comment by tarsius** [comment]
I have just migrated this repository to the Emacsorphanage and added the following note to the README:

I never used this package myself and no longer want to maintain it. I might still fix bugs but all feature requests will be closed. Contact me if you are interested in becoming the new maintainer.
