### ISSUE TITLE
Broken on melpa-stable due to missing transient dependency

### ISSUE THREAD

**Issue by chenz** [emacsorphanage/magit-svn#14]
I think the current version on melpa-stable is broken, and also breaks magit even on a non-git-svn repo, i.e. magit-status fails with `require: Symbol’s function definition is void: define-transient-command`. magit-svn is the only thing installed that uses said function. I guess magit-svn relies on magit to pull in transient, but the version on melpa-stable does not do that yet.

Manually issuing `(require 'transient)` (which I installed separately) fixes the issue.

So I reason the fix is to pull in this dependency explicitly.

**Comment by tarsius** [comment]
Thanks!
