### ISSUE TITLE
"Unpushed git commits" disappears when there are unstaged changes?

### ISSUE THREAD

**Issue by dpkatz** [emacsorphanage/magit-svn#4]
I've noticed an odd behavior with magit-svn and unpushed commits.  In general, if I have local commits that I've not yet pushed back to the upstream SVN repo, they show up in an `Unpushed git commits` section of the magit status buffer - great!  But if I then edit a file and look at the magit-status buffer again, I see the `Unstaged changes` secton but the `Unpushed git commits` section has disappeared.  If I then stage the changes, the `Unpushed git commits` section comes back.  

`M-x magit-version` => `Magit 20150730.1911, Git 2.5.0, Emacs 24.5.1`

Here's a small case where I see it:

```
$ touch test.txt

$ # SET UP SVN REPO
$ mkdir svnrep
$ cd svnrep/
svnrep $ svnadmin create project1
svnrep $ cd ..
$ svn import test.txt file:///path/to/svnrep/project1/test.txt -m "Initial version - Empty"
Adding         test.txt

Committed revision 1.


$ # GIT CLONE OF SVN REPO
$ git svn clone file:///path/to/svnrep/project1 working-git
Initialized empty Git repository in /path/to/working-git/.git/
    A   test.txt
r1 = e4039703d7f411366f38b074fef6f691cfad98d6 (refs/remotes/git-svn)
Checked out HEAD:
  file:///path/to/svnrep/project1 r1
```

Here's a Magit view of the `working-git` clone of the SVN repo:

```
Head:     e403970 master Initial version - Empty
Remote:   r1 from file:///path/to/svnrep/project1
```

If I add a line to the file and check-in with Git (but don't push to SVN) I see this:

```
Head:     660afb4 master Added first line to file.
Remote:   r1 from file:///path/to/svnrep/project1

Unpushed git commits (1)
660afb4 Added first line to file.
```

Now I edit file again, but don't stage or check in yet: - where did `Unpushed git commits` go?

```
Head:     660afb4 master Added first line to file.
Remote:   r1 from file:///path/to/svnrep/project1

Unstaged changes (1)
modified   test.txt
```

Now I stage the edit and `Unpushed git commits` comes back

```
Head:     660afb4 master Added first line to file.
Remote:   r1 from file:///path/to/svnrep/project1

Staged changes (1)
modified   test.txt

Unpushed git commits (1)
660afb4 Added first line to file.
```

**Comment by randymorris** [comment]
I can confirm that **Unpushed git commits** disappears when I have unstaged changes.

I wasn't able to do this exact test due to some version issues between svn and git on my local machine that I couldn't immediately address.  For my test I just created a new git branch (test-magit) based on my master and tested there.  The only difference I saw was that when I have no unstaged changes I have two sections regarding unpushed commits: **Unpushed commits** and **Unpushed git commits**.  When there are unstaged changes the **Unpushed git commits** disappears but **Unpushed commits** is still there.  See below.

No unstaged changes:

```
Unpushed commits (1)
09297f9 test-magit asdf 

Unpushed git commits (1)
09297f9 asdf 
```

With unstaged changes:

```
Unstaged changes (1)
modified   foo.text

Unpushed commits (1)
09297f9 test-magit asdf 
```

Edit: this is with magit-20151114.1619 and magit-svn-20151118.57 from melpa.  Output of `magit-version` is "Magit 20151114.1619, Git 2.6.3, Emacs 25.0.50.1"

**Comment by rudi** [comment]
I see one of `Unpushed git commits` or `Unstaged changes`, as described in the original report.  I do not see an `Unpushed commits` section in either case.

This is with current melpa version of magit and magit-svn (magit-svn patched to fix #5).

**Comment by randymorris** [comment]
I've confirmed that the behavior is exactly the same as in the test.  The double sections were due to the branch that I created tracking master.  Once I removed the merge line from the branch config the behavior was exactly the same as reported.

**Comment by randymorris** [comment]
After a bit of testing, I think this boils down to [these two lines](https://github.com/magit/magit-svn/blob/master/magit-svn.el#L91-L92) failing.  When there are unstaged changes, running `git svn rebase --dry-run` fails to print the "Remote Branch" that `magit-svn-get-ref` is expecting, therefore `magit-insert-svn-unpushed` ends up doing nothing.

**Comment by tarsius** [comment]
Is there a `git svn` subcommand which always prints the required information?

Also could someone please suggest a tiny subversion repository I could clone for testing purposes?

**Comment by tarsius** [comment]
I added a kludge to deal with this.

**Comment by tarsius** [comment]
Turns out `magit-svn.el` once contained the code necessary to do this. I have restored that.
