### ISSUE TITLE
magit-status with magit-svn failing after changes in magit

### ISSUE THREAD

**Issue by randymorris** [emacsorphanage/magit-svn#5]
When running `magit-status` after magit/magit@c5a8c09 the following error happens:

```
magit-insert-svn-remote: Symbol’s function definition is void: magit-insert
```

The issue is that the above commit removed the `magit-insert` function and replaced it with direct calls to `insert`.  magit-svn is using `magit-insert` [here](https://github.com/magit/magit-svn/blob/master/magit-svn.el#L243).

**Comment by rudi** [comment]
I see this as well in the version currently offered via melpa.  `M-x magit-status` fails if the current repo is using git-svn (and magit-svn is active).

**Comment by tarsius** [comment]
Sorry about that, I should have checked whether any extensions were using `magit-insert`, when I removed it.

Does this change cause things to look strange? If I don't here anything to that effect, then I'll tag a release soon.

**Comment by randymorris** [comment]
I honestly don't remember what the remote previously looked like, but I can confirm that it's at least working now.  The subversion revision is using the same face as the shas for git commits so I think all is well.  Thanks.

**Comment by tarsius** [comment]
I should probably also deal with #4 before creating a new release. Can you confirm that issue (please comment there)?
