### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by tarsius** [emacsorphanage/magit-svn#7]
I don't actually use Subversion. So I am not the ideal person to maintain this and am looking for a volunteer to take over.

The new maintainer should take care of the backlog (three issues) and address new issues in a more timely manner than I have in the past (there's about one issue every half a year).

**Comment by tarsius** [comment]
I have taken care of the backlog. So you would have to only deal with new issues and work with me when I make incompatible changes to magit itself.

**Comment by ak-coram** [comment]
I'm using this every other day and know a bit of elisp: I can try to deal with any issues that come up.

**Comment by tarsius** [comment]
> I'm using this every other day and know a bit of elisp: I can try to deal with any issues that come up.

Great!

I am giving up on finding someone who would *commit* to maintaining this. No new issues are being opened anyway.
