### ISSUE TITLE
"N" shortcut in magit-status is not working

### ISSUE THREAD

**Issue by vcmsxs** [emacsorphanage/magit-svn#9]
Using magit-svn  (20151219.547 from elpa), Magit 20161205.438, Git 2.7.4, Emacs 24.5.1, gnu/linux
I have to run magit-svn-popup manualy, the "N" shortcut in magit-status is not working.

Also... svn is absolute pain and agony and they force me to use it at work. Git-svn and your magit-svn is my sweet saviors. Mazel tov on your houses !!

**Comment by tarsius** [comment]
To add the key binding you have to enable the `magit-svn-mode` minor-mode as described in the readme. Did you do that? Otherwise, does `N` do nothing or something else?

**Comment by tarsius** [comment]
I'm gonna assume my suggestion took care of the issue.
